name: CI
on: 
  push:
    branches:
      - kicad-test
      - dcda
      - dcda-git
      - edrawman-cn
      - edrawproject-cn
      - mark-mind
      - serialtool
      - serialtool-git
      - proj2cmake-git
      - mindmaster_cn
      - mindmater_en
      - qserial
  pull_request:
    branches:
      - kicad-test
      - dcda
      - dcda-git
      - edrawman-cn
      - edrawproject-cn
      - mark-mind
      - serialtool
      - serialtool-git
      - proj2cmake-git
      - mindmaster_cn
      - mindmater_en
      - qserial
  schedule:
    - cron: '* 6 * * *'

jobs:
  run-build:
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup
    steps:
      - uses: actions/checkout@v2
      - name: Build Arch Linux package
        uses: taotieren/build-arch-package@master
        with:
          BUILDING: multilib-build
          PKGBUILD: $GITHUB_WORKSPACE/PKGBUILD
          OUTDIR: $HOME/arch-packages
          
      - name: Prepare AUR
        run: |
          mkdir -p ./artifact/AUR/
          #cp -rf $(find $GITHUB_WORKSPACE/ -type f -name "*.sh*") $HOME/arch-packages/
          #bash $HOME/arch-packages/gen.sh -m
          cp -rf $(find $HOME/arch-packages -type f -name "*.zst*") ./artifact/AUR/

      - name: Deliver AUR
        uses: actions/upload-artifact@v2
        with:
          name: AUR
          path: ./artifact/AUR/

      - name: Upload release asset
        if: github.event == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.YOURTOKEN }}
          file: ./artifact/AUR/*
          tag: ${{ github.ref }}
          file_glob: true
